In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [7]:
data = pd.read_csv('auto-mpg.data.csv')

In [8]:
data # Validating data

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0         130    3504          12.0   
1    15.0          8         350.0         165    3693          11.5   
2    18.0          8         318.0         150    3436          11.0   
3    16.0          8         304.0         150    3433          12.0   
4    17.0          8         302.0         140    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0          86    2790          15.6   
394  44.0          4          97.0          52    2130          24.6   
395  32.0          4         135.0          84    2295          11.6   
396  28.0          4         120.0          79    2625          18.6   
397  31.0          4         119.0          82    2720          19.4   

     model_year                         carname  
0            70  1\t"chevrolet chevelle malibu"  
1            70          1\t"buick skylark 320"  
2            70         1\t"plymouth satellite"  
3            70              1\t"amc rebel sst"  
4            70                1\t"ford torino"  
..          ...                             ...  
393          82            1\t"ford mustang gl"  
394          82                  2\t"vw pickup"  
395          82              1\t"dodge rampage"  
396          82                1\t"ford ranger"  
397          82                 1\t"chevy s-10"  

[398 rows x 8 columns]

In [68]:
# Using the scheme of Xb = y
X = data.drop(['mpg', 'carname'], axis = 1).to_numpy() 
X = np.insert(X, 0, np.ones(X.shape[0]), axis = 1) # inserting 1s to account for the slope intercept
y = data.iloc[:, 0].to_numpy() # dependent set

In [69]:
X

array([[1.000e+00, 8.000e+00, 3.070e+02, ..., 3.504e+03, 1.200e+01,
        7.000e+01],
       [1.000e+00, 8.000e+00, 3.500e+02, ..., 3.693e+03, 1.150e+01,
        7.000e+01],
       [1.000e+00, 8.000e+00, 3.180e+02, ..., 3.436e+03, 1.100e+01,
        7.000e+01],
       ...,
       [1.000e+00, 4.000e+00, 1.350e+02, ..., 2.295e+03, 1.160e+01,
        8.200e+01],
       [1.000e+00, 4.000e+00, 1.200e+02, ..., 2.625e+03, 1.860e+01,
        8.200e+01],
       [1.000e+00, 4.000e+00, 1.190e+02, ..., 2.720e+03, 1.940e+01,
        8.200e+01]])

In [70]:
y

array([18. , 15. , 18. , 16. , 17. , 15. , 14. , 14. , 14. , 15. , 15. ,
       14. , 15. , 14. , 24. , 22. , 18. , 21. , 27. , 26. , 25. , 24. ,
       25. , 26. , 21. , 10. , 10. , 11. ,  9. , 27. , 28. , 25. , 25. ,
       19. , 16. , 17. , 19. , 18. , 14. , 14. , 14. , 14. , 12. , 13. ,
       13. , 18. , 22. , 19. , 18. , 23. , 28. , 30. , 30. , 31. , 35. ,
       27. , 26. , 24. , 25. , 23. , 20. , 21. , 13. , 14. , 15. , 14. ,
       17. , 11. , 13. , 12. , 13. , 19. , 15. , 13. , 13. , 14. , 18. ,
       22. , 21. , 26. , 22. , 28. , 23. , 28. , 27. , 13. , 14. , 13. ,
       14. , 15. , 12. , 13. , 13. , 14. , 13. , 12. , 13. , 18. , 16. ,
       18. , 18. , 23. , 26. , 11. , 12. , 13. , 12. , 18. , 20. , 21. ,
       22. , 18. , 19. , 21. , 26. , 15. , 16. , 29. , 24. , 20. , 19. ,
       15. , 24. , 20. , 11. , 20. , 21. , 19. , 15. , 31. , 26. , 32. ,
       25. , 16. , 16. , 18. , 16. , 13. , 14. , 14. , 14. , 29. , 26. ,
       26. , 31. , 32. , 28. , 24. , 26. , 24. , 26

In [92]:
# Need to create K-Folds
K = 10

# Evenly partition the both y and X into 10 partitions
np.random.seed(X.shape[0])
indices = np.random.permutation(X.shape[0]) # Randomizing indices to shuffle rows
print(indices)

[173  81  28 149 234 181 210 306 332 395  43 171 123  87 186 144 243  97
  48 334 369 328 266   8 286  98  71 325  23 341 359 276 280 230  85 168
  30   6 311 111 257 175 127 302  80 295 141 387 337  26 226 348 131  31
 391 293 107 324  59 184 245 104 176 333  34 335 313 331 166 222 146 198
  54 237 138 216 296 194 269 373 157 124 118  50  84 250 221 255  44 347
 389  77 203  14 388 356  16 148  36 119 103 218 154   0 264 253 349 288
 142 231 190 319  56 174 256 344 364 110  55 136  62 208 375  20 273 214
  46 165 120 241 224 354  19   3 129  91 343  45 270 294 362  94  70  90
  86 244 152  49 114  99  92 262 316 345 180 281 140 381 368 272 350 300
 105 161 378 162 125 367  42  15 109 309 342 151 275 301  63  24 263 252
 258 303   1 205  37  78 249   5 132 363 383   7 172 260  96  25 312 188
 113 159   4 307 279 317 238 285 191 200 259 147 115  95 396  66  75 323
 305 101  13 357 153  61 351 164 261  69  33 121 233 374 267  89 380 376
 100 211 299 390 195 366 327 352 134 339  21 283  7

In [96]:
# Split into groups of 10
indices = np.array_split(indices, K)

In [97]:
print(indices)

[array([173,  81,  28, 149, 234, 181, 210, 306, 332, 395,  43, 171, 123,
        87, 186, 144, 243,  97,  48, 334, 369, 328, 266,   8, 286,  98,
        71, 325,  23, 341, 359, 276, 280, 230,  85, 168,  30,   6, 311,
       111]), array([257, 175, 127, 302,  80, 295, 141, 387, 337,  26, 226, 348, 131,
        31, 391, 293, 107, 324,  59, 184, 245, 104, 176, 333,  34, 335,
       313, 331, 166, 222, 146, 198,  54, 237, 138, 216, 296, 194, 269,
       373]), array([157, 124, 118,  50,  84, 250, 221, 255,  44, 347, 389,  77, 203,
        14, 388, 356,  16, 148,  36, 119, 103, 218, 154,   0, 264, 253,
       349, 288, 142, 231, 190, 319,  56, 174, 256, 344, 364, 110,  55,
       136]), array([ 62, 208, 375,  20, 273, 214,  46, 165, 120, 241, 224, 354,  19,
         3, 129,  91, 343,  45, 270, 294, 362,  94,  70,  90,  86, 244,
       152,  49, 114,  99,  92, 262, 316, 345, 180, 281, 140, 381, 368,
       272]), array([350, 300, 105, 161, 378, 162, 125, 367,  42,  15, 109, 309, 342,
       

In [120]:
print(X[indices[0]])

[[1.000e+00 4.000e+00 1.190e+02 9.700e+01 2.545e+03 1.700e+01 7.500e+01]
 [1.000e+00 4.000e+00 9.700e+01 9.200e+01 2.288e+03 1.700e+01 7.200e+01]
 [1.000e+00 8.000e+00 3.040e+02 1.930e+02 4.732e+03 1.850e+01 7.000e+01]
 [1.000e+00 4.000e+00 1.200e+02 9.700e+01 2.489e+03 1.500e+01 7.400e+01]
 [1.000e+00 4.000e+00 1.510e+02 8.800e+01 2.740e+03 1.600e+01 7.700e+01]
 [1.000e+00 4.000e+00 9.100e+01 5.300e+01 1.795e+03 1.750e+01 7.500e+01]
 [1.000e+00 6.000e+00 1.560e+02 1.080e+02 2.930e+03 1.550e+01 7.600e+01]
 [1.000e+00 6.000e+00 1.730e+02 1.150e+02 2.595e+03 1.130e+01 7.900e+01]
 [1.000e+00 4.000e+00 8.900e+01 6.200e+01 1.845e+03 1.530e+01 8.000e+01]
 [1.000e+00 4.000e+00 1.350e+02 8.400e+01 2.295e+03 1.160e+01 8.200e+01]
 [1.000e+00 8.000e+00 4.000e+02 1.700e+02 4.746e+03 1.200e+01 7.100e+01]
 [1.000e+00 4.000e+00 1.340e+02 9.600e+01 2.702e+03 1.350e+01 7.500e+01]
 [1.000e+00 6.000e+00 1.560e+02 1.220e+02 2.807e+03 1.350e+01 7.300e+01]
 [1.000e+00 8.000e+00 3.500e+02 1.450e+02 3.988e+03

In [ ]:
# Performing K-Fold C